global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'go-auth'
    static_configs:
      - targets: ['go-auth:8081']
        labels:
          service: 'go-auth-service'
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
