// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-game/internal/app"
	"go-game/internal/config"
	"go-game/internal/services"
	"go-game/pkg/kafka"
	"go-game/pkg/webrtc"
)

// Injectors from wire.go:

func Initialize() (*Dependenсies, error) {
	configConfig := config.New()
	producer := kafka.NewProducer(configConfig)
	rtcManager := webrtc.NewRTCManager(producer, configConfig)
	messageService := services.NewMessageService(rtcManager)
	consumer, err := kafka.NewConsumer(configConfig, messageService)
	if err != nil {
		return nil, err
	}
	dependenсies := &Dependenсies{
		Producer:       producer,
		Consumer:       consumer,
		MessageService: messageService,
		RTCManager:     rtcManager,
	}
	return dependenсies, nil
}

// wire.go:

type Dependenсies struct {
	Producer       app.KProducer
	Consumer       app.KConsumer
	MessageService app.MessageService
	RTCManager     *webrtc.RTCManager
}
