// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-messages/internal/app"
	"go-messages/internal/config"
	"go-messages/internal/handlers"
	"go-messages/internal/services"
	"go-messages/pkg/kafka"
	"go-messages/pkg/mongo"
)

// Injectors from wire.go:

func Initialize() (*Dependenсies, error) {
	configConfig := config.New()
	producer := kafka.NewProducer(configConfig)
	mongoRepository, err := mongo.New(configConfig)
	if err != nil {
		return nil, err
	}
	messageService, err := services.New(mongoRepository)
	if err != nil {
		return nil, err
	}
	consumer, err := kafka.NewConsumer(configConfig, messageService)
	if err != nil {
		return nil, err
	}
	kafkaHendler := handlers.InitKafkaHandlers(consumer, producer)
	dependenсies := &Dependenсies{
		Producer:        producer,
		Consumer:        consumer,
		MongoRepository: mongoRepository,
		KafkaHendler:    kafkaHendler,
	}
	return dependenсies, nil
}

// wire.go:

type Dependenсies struct {
	Producer        app.KProducer
	Consumer        app.KConsumer
	MongoRepository app.MongoRepository
	KafkaHendler    *handlers.KafkaHendler
}
