// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-messages/internal/config"
	"go-messages/internal/handlers"
	"go-messages/pkg/kafka"
)

// Injectors from wire.go:

func Initialize() *Dependenсies {
	configConfig := config.New()
	producer := kafka.NewProducer(configConfig)
	consumer := kafka.NewConsumer(configConfig)
	kafkaHendler := handlers.InitKafkaHandlers(consumer, producer)
	dependenсies := &Dependenсies{
		Producer:     producer,
		Consumer:     consumer,
		KafkaHendler: kafkaHendler,
	}
	return dependenсies
}

// wire.go:

type Dependenсies struct {
	Producer     *kafka.Producer
	Consumer     *kafka.Consumer
	KafkaHendler *handlers.KafkaHendler
}
